# Generated by Django 5.2.5 on 2025-08-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(max_length=10, verbose_name='likes')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='user_name')),
                ('password', models.CharField(max_length=10, verbose_name='user_pwd')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='user_gender')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vue_Dj1.userlike', verbose_name='preference')),
            ],
        ),
    ]
