# Generated by Django 5.2.5 on 2025-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=10, verbose_name='admin_name')),
                ('admin_password', models.CharField(max_length=10, verbose_name='admin_pwd')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
    ]
