# Generated by Django 5.2.5 on 2025-08-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0002_admin_rename_name_user_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'male'), (2, 'female')], verbose_name='user_gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vue_Dj1.userlike', verbose_name='preference'),
        ),
    ]
