# Generated by Django 5.2.5 on 2025-08-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0003_alter_user_gender_alter_user_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], null=True, verbose_name='user_gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vue_Dj1.userlike', verbose_name='preference'),
        ),
    ]
