# Generated by Django 5.2.5 on 2025-08-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0004_alter_user_gender_alter_user_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('publisher', models.CharField(max_length=10, verbose_name='publisher')),
                ('detail', models.CharField(max_length=500, verbose_name='detail')),
                ('date', models.DateField(max_length=20, verbose_name='date')),
                ('views', models.SmallIntegerField(verbose_name='views')),
                ('images', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='user_gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vue_Dj1.userlike', verbose_name='preference'),
        ),
    ]
