# Generated by Django 5.2.5 on 2025-08-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0005_content_alter_user_gender_alter_user_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sort',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
