# Generated by Django 5.2.5 on 2025-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0006_content_sort_alter_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.CharField(max_length=20, verbose_name='date'),
        ),
    ]
