# Generated by Django 5.2.5 on 2025-08-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0007_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='user_gender'),
        ),
    ]
