# Generated by Django 5.2.5 on 2025-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0009_alter_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
