# Generated by Django 5.2.5 on 2025-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0010_alter_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='midia'),
        ),
    ]
