# Generated by Django 5.2.5 on 2025-08-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0011_alter_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=models.CharField(max_length=1500, verbose_name='detail'),
        ),
    ]
