# Generated by Django 5.2.5 on 2025-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0012_alter_content_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=models.CharField(max_length=10000, verbose_name='detail'),
        ),
    ]
