# Generated by Django 5.2.5 on 2025-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0013_alter_content_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='friends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
