# Generated by Django 5.2.5 on 2025-08-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0014_content_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='friends',
            new_name='focus',
        ),
    ]
