# Generated by Django 5.2.5 on 2025-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0015_rename_friends_content_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='focus',
        ),
        migrations.AddField(
            model_name='user',
            name='focus',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
