# Generated by Django 5.2.5 on 2025-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0016_remove_content_focus_user_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='focus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
