# Generated by Django 5.2.5 on 2025-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0017_alter_user_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
