# Generated by Django 5.2.5 on 2025-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0018_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_midia'),
        ),
    ]
