# Generated by Django 5.2.5 on 2025-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0020_alter_content_images_alter_user_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='midia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_midia'),
        ),
    ]
