# Generated by Django 5.2.5 on 2025-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_Dj1', '0022_alter_content_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_media'),
        ),
    ]
